server:
  port: 8765

spring:
  application:
    name: admin-server
  boot:
    admin:
      discovery:
        ignored-services:
          - GATEWAY-SERVER
          - ADMIN-SERVER

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: admin-server
